name: "P6 GHA: Setups Node"
description: "P6 GHA: Setups Node"
author: "Philip M. Gollucci"

inputs:
  node-version:
    description: "Node.js version to install (e.g., 24.9.0)"
    required: false
    default: "24.9.0"

runs:
  using: "composite"
  steps:
    - name: Install Node.js
      shell: bash
      run: |
        NODE_VERSION="${{ inputs.node-version }}"
        curl -fsSL "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz" -o "node-v${NODE_VERSION}-linux-x64.tar.xz"
        sudo tar -xJf "node-v${NODE_VERSION}-linux-x64.tar.xz" -C /usr/local
        rm -f "node-v${NODE_VERSION}-linux-x64.tar.xz"
        echo "/usr/local/node-v${NODE_VERSION}-linux-x64/bin" >> $GITHUB_PATH

    - name: Corepack
      shell: bash
      run: |
        sudo corepack enable
        sudo corepack prepare yarn@latest --activate

    - name: Restore NPM node_modules
      uses: actions/cache/restore@v5.0.1
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Check Node
      shell: bash
      run: |
        NODE_VERSION="${{ inputs.node-version }}"
        set +e
        ls -alFh "/usr/local/node-v${NODE_VERSION}-linux-x64/bin"
        which node
        which npm
        which yarn
        which corepack
        node -v
        npm -v
        yarn --version
        corepack --version
        echo $PATH

    - name: Install pnpm and dependencies
      shell: bash
      run: |
        if [ -e package.json ]; then
          yarn install
          yarn explain peer-requirements
        fi
    - name: Cache NPM dependencies
      uses: actions/cache@v5.0.1
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
