name: "P6 GHA: Setups Node"
description: "P6 GHA: Setups Node"
author: "Philip M. Gollucci"
runs:
  using: "composite"
  steps:
    - name: Install Node.js
      shell: bash
      run: |
        curl -fsSL https://nodejs.org/dist/v22.11.0/node-v22.11.0-linux-x64.tar.xz -o node-v22.11.0-linux-x64.tar.xz
        sudo tar -xJf node-v22.11.0-linux-x64.tar.xz -C /usr/local
        rm -f node-v22.11.0-linux-x64.tar.xz
        echo "/usr/local/node-v22.11.0-linux-x64/bin" >> $GITHUB_PATH
    - name: Corepack
      shell: bash
      run: |
        sudo corepack enable
        sudo corepack prepare yarn@latest --activate
    - name: Restore NPM node_modules
      uses: actions/cache/restore@v4.1.2
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
    - name: Check Node
      shell: bash
      run: |
        set +e
        ls -alFh /usr/local/node-v22.11.0-linux-x64/bin
        which node
        which npm
        which yarn
        which corepack
        node -v
        npm -v
        yarn --version
        corepack --version
        echo $PATH
    - name: Install pnpm and dependencies
      shell: bash
      run: |
        yarn install
        yarn explain peer-requirements
    - name: Cache NPM dependencies
      uses: actions/cache@v4.1.2
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
